name: GitHub Actions with Terraform Cloud Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
env:
  tf_actions_working_dir: environments/dev
jobs:
  Test-GitHub-Actions-with-Terraform-Cloud:
    runs-on: [ubuntu-latest]
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
     
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      
      # - name: Terraform Plan
      #   id: plan
      #   run: terraform plan -no-color -var="ec2_runner_github_pat=${{ secrets.PAT_RUNNER_REGISTRATION_ORG }}"
      #   continue-on-error: false

      # - name: Terraform Apply
      #   id: apply
      #   run: terraform apply -auto-approve -no-color -var="ec2_runner_github_pat=${{ secrets.PAT_RUNNER_REGISTRATION_ORG }}"
      #   continue-on-error: true
      
      - name: Terraform Destroy
        id: destroy
        run: terraform apply -destroy -auto-approve -no-color -var="ec2_runner_github_pat=${{ secrets.PAT_RUNNER_REGISTRATION_ORG }}"
        continue-on-error: true

      - name: Job Status
        run: echo "This job's status is ${{ job.status }}."